name: Hello World Workflow

on:
  workflow_dispatch:    # Allows manual triggering
    inputs:
      greeting:         # Input parameter name
        description: "Enter your greeting"
        required: true

  #push:                 # Automatically triggers on a push
   # branches:
    #  - main            # Specify the branch (e.g., main)

jobs:
  hello-world-job:
    runs-on: ubuntu-latest # Use GitHub-hosted runner (Ubuntu)
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Print the custom greeting to the console
      - name: Say Hello World
        run: echo "${{ github.event.inputs.greeting }}"
