name: Hello World Workflow

on:
  workflow_dispatch: # Allows manual triggering of the workflow
  push:              # Triggers the workflow automatically on a push
    branches:
      - main
jobs:
  hello-world-job:
    runs-on: ubuntu-latest # Use GitHub-hosted runner (Ubuntu)
    
    steps:
      # Step 1: Checkout the repository code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Step 2: Print "Hello World" to the console
      - name: Say Hello World
        run: echo "Hello, World from GitHub-hosted runner!"
